// Curated "famous" furniture search terms — common phrases shoppers type that
// aren't represented as standalone category names (bed sizes, sofa/set
// variants, etc.). Included even if no current product matches yet, so the
// vocabulary stays ready as the catalog grows. Merged with the
// category-derived vocabulary in search.controller.js to build the
// autocomplete keyword list.
export const CURATED_SEARCH_KEYWORDS = [
  // Beds & mattresses
  'Single Bed',
  'Double Bed',
  'Queen Bed',
  'King Bed',
  'Bunk Bed',
  'Twin Bed',
  'Murphy Bed',
  'Platform Bed',
  'Storage Bed',
  'Sofa Bed',
  'Trundle Bed',
  'Canopy Bed',
  'Adjustable Bed',
  'Bed Frame',
  'Headboard',
  'Mattress',
  'Memory Foam Mattress',
  'Mattress Topper',
  'Bassinet',
  'Changing Table',

  // Sofas & seating
  'Sofa',
  'Sofa Set',
  'Sectional Sofa',
  'Corner Sofa',
  'Loveseat',
  'Sleeper Sofa',
  'Reclining Sofa',
  'Sofa Recliner',
  'Modular Sofa',
  'Futon',
  'L-Shaped Sofa',
  'U-Shaped Sofa',
  'Convertible Sofa',
  'Chesterfield Sofa',
  'Settee',
  'Recliner Chair',
  'Accent Chair',
  'Armchair',
  'Rocking Chair',
  'Gaming Chair',
  'Lounge Chair',
  'Chaise Lounge',
  'Ottoman',
  'Pouf',
  'Bean Bag Chair',
  'Bar Stool',
  'Bench',
  'Stool',
  'Swivel Chair',
  'Wingback Chair',
  'Club Chair',
  'Folding Chair',
  'Massage Chair',
  'Glider Chair',
  'Egg Chair',
  'High Chair',

  // Room sets
  'Living Room Set',
  'Bedroom Set',
  'Dining Set',
  'Patio Set',
  'Bistro Set',
  'Sectional Set',
  'Office Set',
  'Kids Bedroom Set',

  // Tables
  'Side Table',
  'End Table',
  'Console Table',
  'Accent Table',
  'Conference Table',
  'Folding Table',
  'Bistro Table',
  'Round Table',
  'Square Table',
  'Extendable Table',
  'Nesting Tables',
  'Pub Table',
  'Drafting Table',
  'Vanity Table',
  'Picnic Table',
  'Card Table',

  // Storage
  'Bookshelf',
  'Chest of Drawers',
  'Storage Cabinet',
  'Shelving Unit',
  'Shoe Cabinet',
  'Shoe Rack',
  'Display Cabinet',
  'Cabinet',
  'Shelf',
  'Closet Organizer',
  'Garment Rack',
  'Coat Rack',
  'Hall Tree',
  'Entryway Bench',
  'Storage Bench',
  'Storage Ottoman',
  'Storage Trunk',
  'Toy Chest',
  'Pantry Cabinet',
  'Kitchen Cart',
  'Bar Cart',
  'Wine Rack',
  'Media Console',

  // Office
  'Office Desk',
  'Computer Desk',
  'Writing Desk',
  'Corner Desk',
  'Desk Organizer',
  'Monitor Stand',
  'Room Divider',

  // Outdoor
  'Patio Furniture',
  'Garden Furniture',
  'Sun Lounger',
  'Outdoor Sofa',
  'Hammock',
  'Outdoor Bench',
  'Patio Chair',
  'Outdoor Table',
  'Outdoor Rug',
  'Fire Pit',
  'Adirondack Chair',
  'Porch Swing',
  'Gazebo',
  'Pool Lounger',

  // Kids
  'Kids Bed',
  'Toddler Bed',
  'Crib',
  'Bean Bag',
  'Toy Storage',
  'Kids Bookshelf',
  'Rocking Horse',

  // Lighting
  'Ceiling Light',
  'Wall Lamp',
  'Desk Lamp',
  'Wall Sconce',
  'Reading Lamp',
  'Night Light',
  'Outdoor Lighting',

  // Decor & textiles
  'Rug',
  'Area Rug',
  'Curtains',
  'Cushion',
  'Throw Pillow',
  'Throw Blanket',
  'Blanket',
  'Comforter',
  'Bedding Set',
  'Pillow',
  'Wall Art',
  'Wall Shelf',
  'Wall Decor',
  'Picture Frame',
  'Vase',
  'Candle Holder',
  'Clock',
  'Plant Stand',
  'Door Mat',
  'Tapestry',

  // Bathroom
  'Bathroom Cabinet',
  'Bathroom Mirror',
  'Bathroom Storage',
  'Towel Rack',
  'Towel Bar',
  'Shower Caddy',
  'Bath Mat',
  'Linen Tower',
  'Laundry Hamper',

  // Kitchen & dining
  'Kitchen Island',
  'China Hutch',
  'Wine Cabinet',
  'Breakfast Nook',
];
