// Curated furniture search terms — common phrases shoppers type that
// aren't represented as standalone category names. Merged with the
// auto-derived category vocabulary in keywords.service.js to build the
// autocomplete keyword list.
export const CURATED_SEARCH_KEYWORDS = [
  // ─── Beds & Bedroom ──────────────────────────────────────────────────
  'Single Bed',
  'Double Bed',
  'Queen Bed',
  'King Bed',
  'Bunk Bed',
  'Twin Bed',
  'Murphy Bed',
  'Platform Bed',
  'Storage Bed',
  'Sofa Bed',
  'Trundle Bed',
  'Canopy Bed',
  'Adjustable Bed',
  'Bed Frame',
  'Headboard',
  'Footboard',
  'Sleigh Bed',
  'Panel Bed',
  'Daybed',
  'Day Bed',
  'Media Chest',
  'Armoire',
  'Chest of Drawers',
  'Dresser',
  'Nightstand',
  'Vanity',
  'Bedroom Bench',
  'Kids Bunk Bed',
  'Loft Bed',
  'Toddler Bed',
  'Crib',

  // ─── Mattresses & Bedding ────────────────────────────────────────────
  'Mattress',
  'Twin Mattress',
  'Twin XL Mattress',
  'Full Mattress',
  'Queen Mattress',
  'King Mattress',
  'California King Mattress',
  'California King',
  'Memory Foam Mattress',
  'Hybrid Mattress',
  'Innerspring Mattress',
  'Mattress in a Box',
  'Mattress Topper',
  'Box Spring',
  'Foundation',
  'Bed Foundation',
  'Adjustable Base',
  'Adjustable Bed Base',
  'Bed in a Box',
  'Bedding Set',
  'Comforter',
  'Pillow',
  'Throw Pillow',
  'Throw Blanket',
  'Blanket',
  'Duvet',

  // ─── Sofas & Living Room Seating ─────────────────────────────────────
  'Sofa',
  'Sofa Set',
  'Living Room Set',
  'Sectional Sofa',
  'Corner Sofa',
  'Loveseat',
  'Sleeper Sofa',
  'Pull Out Sofa',
  'Reclining Sofa',
  'Sofa Recliner',
  'Modular Sofa',
  'Futon',
  'L-Shaped Sofa',
  'U-Shaped Sofa',
  'Convertible Sofa',
  'Chesterfield Sofa',
  'Recliner Chair',
  'Accent Chair',
  'Armchair',
  'Rocking Chair',
  'Lounge Chair',
  'Chaise Lounge',
  'Ottoman',
  'Pouf',
  'Bean Bag Chair',
  'Swivel Chair',
  'Wingback Chair',
  'Club Chair',
  'Glider Chair',
  'Settee',

  // ─── Tables ──────────────────────────────────────────────────────────
  'Side Table',
  'End Table',
  'Console Table',
  'Accent Table',
  'Coffee Table',
  'Coffee Table Set',
  'Sofa Table',
  'Nesting Tables',
  'Round Coffee Table',
  'Extendable Table',
  'Folding Table',
  'Pub Table',
  'Drafting Table',
  'Vanity Table',

  // ─── Dining & Kitchen ────────────────────────────────────────────────
  'Dining Set',
  'Dining Table',
  'Dining Chair',
  'Bar Stool',
  'Counter Stool',
  'Bar Chair',
  'Counter Height Stool',
  'Breakfast Bar Stool',
  'Dining Bench',
  'China Cabinet',
  'China Hutch',
  'Curio Cabinet',
  'Display Cabinet',
  'Sideboard',
  'Buffet',
  'Server',
  'Kitchen Island',
  'Kitchen Cart',
  'Bar Cart',
  'Wine Rack',
  'Wine Cabinet',
  'Breakfast Nook',

  // ─── Office ──────────────────────────────────────────────────────────
  'Office Desk',
  'Computer Desk',
  'Writing Desk',
  'Corner Desk',
  'Executive Desk',
  'Standing Desk',
  'L-Shaped Desk',
  'Home Office Set',
  'Gaming Desk',
  'Bookcase',
  'Bookshelf',
  'Filing Cabinet',
  'Office Chair',

  // ─── Outdoor ─────────────────────────────────────────────────────────
  'Patio Furniture',
  'Outdoor Furniture',
  'Garden Furniture',
  'Patio Set',
  'Conversation Set',
  'Patio Conversation Set',
  'Outdoor Sofa',
  'Outdoor Loveseat',
  'Outdoor Chair',
  'Patio Chair',
  'Adirondack Chair',
  'Outdoor Dining Set',
  'Patio Dining Set',
  'Outdoor Table',
  'Patio Table',
  'Sun Lounger',
  'Chaise Lounge',
  'Pool Lounger',
  'Outdoor Chaise',
  'Outdoor Bench',
  'Outdoor Fireplace',
  'Fire Pit',
  'Porch Swing',
  'Hammock',
  'Outdoor Accessories',

  // ─── Storage ─────────────────────────────────────────────────────────
  'Storage Cabinet',
  'Shelving Unit',
  'Media Console',
  'TV Stand',
  'Entertainment Center',
  'Shoe Cabinet',
  'Shoe Rack',
  'Closet Organizer',
  'Coat Rack',
  'Hall Tree',
  'Entryway Bench',
  'Storage Bench',
  'Storage Ottoman',
  'Storage Trunk',
  'Toy Chest',
  'Pantry Cabinet',
  'Cabinet',
  'Shelf',

  // ─── Decor & Accessories ─────────────────────────────────────────────
  'Home Decor',
  'Wall Decor',
  'Wall Art',
  'Wall Hanging',
  'Canvas Art',
  'Picture Frame',
  'Accent Mirror',
  'Decorative Mirror',
  'Wall Mirror',
  'Clock',
  'Wall Clock',
  'Artificial Plant',
  'Fake Plant',
  'Faux Plant',
  'Room Divider',
  'Folding Screen',
  'Accent Bench',
  'Entryway Furniture',
  'Entryway Table',
  'Vase',
  'Candle Holder',
  'Decorative Tray',

  // ─── Rugs ────────────────────────────────────────────────────────────
  'Rug',
  'Area Rug',
  'Runner Rug',
  'Shag Rug',
  'Persian Rug',
  'Outdoor Rug',
  'Living Room Rug',
  'Bedroom Rug',
  'Indoor Rug',

  // ─── Lighting ────────────────────────────────────────────────────────
  'Floor Lamp',
  'Table Lamp',
  'Desk Lamp',
  'Reading Lamp',
  'Night Light',
  'Ceiling Light',
  'Wall Lamp',
  'Wall Sconce',
  'Outdoor Lighting',

  // ─── Kids ────────────────────────────────────────────────────────────
  'Kids Furniture',
  'Kids Bedroom Set',
  'Kids Bed',
  'Bunk Bed',
  'Kids Bunk Bed',
  'Kids Desk',
  'Kids Chair',
  'Kids Storage',
  'Kids Bookshelf',
  'Toy Storage',
  'Bean Bag',

  // ─── Common modifiers shoppers add ───────────────────────────────────
  'Modern Sofa',
  'Modern Bedroom',
  'Modern Dining',
  'Mid Century Modern',
  'Farmhouse',
  'Industrial',
  'Rustic',
  'White Dresser',
  'Gray Sofa',
  'Sectional with Chaise',
  'King Bedroom Set',
  'Queen Bedroom Set',
];
