// src/components/orders/OrderCard.js
'use client';

import { useState } from 'react';
import { 
  ORDER_STATUS, 
  getNextStatuses
} from '@/lib/constants/orderStatus';
import { Package, ChevronDown } from 'lucide-react';

export default function OrderCard({ order, onStatusUpdate, onRowClick }) {
  const [showStatusDropdown, setShowStatusDropdown] = useState(false);

  const status = ORDER_STATUS[order.status] || ORDER_STATUS.PENDING;
  const StatusIcon = status.icon;
  const nextStatuses = getNextStatuses(order.status);

  // Format date
  const orderDate = new Date(order.createdAt).toLocaleDateString('en-US', {
    month: 'short',
    day: 'numeric',
    year: 'numeric',
  });

  // Get items info
  const items = order.items || [];
  const itemCount = items.length;
  const firstItem = items[0];

  // Get main product SKU
  const mainSKU = firstItem?.product?.sku || firstItem?.sku || 'N/A';
  const mainProductName = firstItem?.product?.name || 'Product';

  // Calculate vendor earnings (after 6% commission)
  const earnings = (order.total || 0) * (1 - (order.commissionRate || 0.06));

  // Total quantity
  const totalQty = items.reduce((sum, item) => sum + (item.quantity || 1), 0);

  // Handle status change - tracking is auto-generated by backend
  const handleStatusChange = (e, newStatus) => {
    e.stopPropagation();
    setShowStatusDropdown(false);
    onStatusUpdate?.(order.id, newStatus);
  };

  // Handle status button click
  const handleStatusClick = (e) => {
    e.stopPropagation();
    if (nextStatuses.length > 0) {
      setShowStatusDropdown(!showStatusDropdown);
    }
  };

  // Handle row click
  const handleRowClick = () => {
    onRowClick?.(order);
  };

  return (
    <tr 
      onClick={handleRowClick}
      className="hover:bg-blue-50 border-b border-gray-100 last:border-0 cursor-pointer transition-colors"
    >
      {/* Order Info */}
      <td className="px-4 py-4">
        <div>
          <p className="font-semibold text-gray-900">
            #{order.orderNumber || order.id?.slice(0, 8).toUpperCase()}
          </p>
          <p className="text-xs text-gray-500 mt-0.5">
            {orderDate}
          </p>
          {/* Show tracking number if exists */}
          {order.trackingNumber && (
            <p className="text-xs text-blue-600 font-mono mt-0.5">
              {order.trackingNumber}
            </p>
          )}
        </div>
      </td>

      {/* Product & SKU */}
      <td className="px-4 py-4">
        <div className="flex items-center gap-3">
          {/* Product Image */}
          <div className="w-10 h-10 bg-gray-100 rounded-lg overflow-hidden flex-shrink-0">
            {firstItem?.product?.images?.[0] ? (
              <img 
                src={firstItem.product.images[0]} 
                alt={mainProductName}
                className="w-full h-full object-cover"
              />
            ) : (
              <div className="w-full h-full flex items-center justify-center">
                <Package className="w-5 h-5 text-gray-400" />
              </div>
            )}
          </div>
          
          {/* Product Info */}
          <div className="min-w-0">
            <p className="font-medium text-gray-900 truncate max-w-[200px]">
              {mainProductName}
            </p>
            <p className="text-xs font-mono text-blue-600 font-semibold">
              SKU: {mainSKU}
            </p>
          </div>

          {/* More items badge */}
          {itemCount > 1 && (
            <span className="px-2 py-0.5 bg-gray-100 text-gray-600 text-xs font-medium rounded">
              +{itemCount - 1}
            </span>
          )}
        </div>
      </td>

      {/* Qty */}
      <td className="px-4 py-4 text-center">
        <span className="font-semibold text-gray-900">{totalQty}</span>
      </td>

      {/* Total */}
      <td className="px-4 py-4">
        <div className="text-right">
          <p className="font-semibold text-gray-900">
            ${(order.total || 0).toFixed(2)}
          </p>
          <p className="text-xs text-green-600 font-medium">
            Earnings: ${earnings.toFixed(2)}
          </p>
        </div>
      </td>

      {/* Status - Clickable Dropdown */}
      <td className="px-4 py-4">
        <div className="relative inline-block">
          <button
            onClick={handleStatusClick}
            disabled={nextStatuses.length === 0}
            className={`
              inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-semibold
              transition-all border-2
              ${status.badgeBg} ${status.badgeText} ${status.borderColor}
              ${nextStatuses.length > 0 
                ? 'cursor-pointer hover:shadow-md' 
                : 'cursor-default'
              }
            `}
          >
            <StatusIcon className="w-3.5 h-3.5" />
            {status.label}
            {nextStatuses.length > 0 && (
              <ChevronDown className={`w-3 h-3 ml-0.5 transition-transform ${showStatusDropdown ? 'rotate-180' : ''}`} />
            )}
          </button>

          {/* Status Dropdown */}
          {showStatusDropdown && nextStatuses.length > 0 && (
            <>
              <div 
                className="fixed inset-0 z-10" 
                onClick={(e) => {
                  e.stopPropagation();
                  setShowStatusDropdown(false);
                }} 
              />
              <div className="absolute left-0 mt-2 w-52 bg-white rounded-xl shadow-xl border border-gray-200 py-2 z-20">
                <p className="px-4 py-2 text-xs font-semibold text-gray-400 uppercase tracking-wide">
                  Update Status
                </p>
                {nextStatuses.map((nextStatus) => {
                  const nextConfig = ORDER_STATUS[nextStatus];
                  const NextIcon = nextConfig?.icon;
                  return (
                    <button
                      key={nextStatus}
                      onClick={(e) => handleStatusChange(e, nextStatus)}
                      className={`
                        w-full px-4 py-2.5 text-left text-sm font-medium
                        hover:bg-gray-50 flex items-center gap-3 transition-colors
                      `}
                    >
                      <span className={`p-1.5 rounded-lg ${nextConfig.badgeBg}`}>
                        {NextIcon && <NextIcon className={`w-4 h-4 ${nextConfig.badgeText}`} />}
                      </span>
                      <span className="text-gray-700">{nextConfig?.label}</span>
                    </button>
                  );
                })}
              </div>
            </>
          )}
        </div>
      </td>
    </tr>
  );
}