// src/app/dashboard/orders/page.js
'use client';

import { useState } from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { ordersService } from '@/lib/api/orders.service';
import { ORDER_STATUS } from '@/lib/constants/orderStatus';
import { OrdersTable, StatusTabs, OrderDetailsModal } from '@/components/orders';
import { 
  Search, 
  RefreshCw,
  AlertCircle,
  Inbox
} from 'lucide-react';
import toast from 'react-hot-toast';

export default function OrdersPage() {
  const [statusFilter, setStatusFilter] = useState('all');
  const [searchQuery, setSearchQuery] = useState('');
  const [page, setPage] = useState(1);
  const [selectedOrder, setSelectedOrder] = useState(null);
  const limit = 20;

  const queryClient = useQueryClient();

  // Fetch orders
  const { 
    data, 
    isLoading, 
    isError, 
    error,
    refetch,
    isFetching 
  } = useQuery({
    queryKey: ['vendor-orders', statusFilter, page],
    queryFn: () => ordersService.getVendorOrders({ 
      page, 
      limit, 
      status: statusFilter === 'all' ? null : statusFilter 
    }),
    staleTime: 30 * 1000,
    refetchOnWindowFocus: true,
  });

  // Status update mutation
  // Backend auto-generates tracking number when status = SHIPPED
  const statusMutation = useMutation({
    mutationFn: ({ orderId, status }) => {
      console.log('🔄 Mutation called:', orderId, status);
      return ordersService.updateStatus(orderId, status);
    },
    onSuccess: (data) => {
      queryClient.invalidateQueries(['vendor-orders']);
      // Show tracking number if generated
      if (data?.order?.trackingNumber) {
        toast.success(`Status updated! Tracking: ${data.order.trackingNumber}`);
      } else {
        toast.success('Status updated!');
      }
    },
    onError: (error) => {
      console.error('❌ Status update error:', error);
      toast.error(error?.message || error?.error || 'Failed to update status');
    },
  });

  // Extract data
  const orders = data?.orders || [];
  const pagination = data?.pagination || { page: 1, totalPages: 1, totalCount: 0 };

  // Status counts
  const statusCounts = orders.reduce((acc, order) => {
    acc[order.status] = (acc[order.status] || 0) + 1;
    acc.all = (acc.all || 0) + 1;
    return acc;
  }, { all: orders.length });

  // Search filter
  const filteredOrders = orders.filter(order => {
    if (!searchQuery.trim()) return true;
    const query = searchQuery.toLowerCase();
    return (
      order.orderNumber?.toLowerCase().includes(query) ||
      order.id?.toLowerCase().includes(query) ||
      order.trackingNumber?.toLowerCase().includes(query) ||
      order.items?.some(item => 
        item.product?.name?.toLowerCase().includes(query) ||
        item.product?.sku?.toLowerCase().includes(query) ||
        item.sku?.toLowerCase().includes(query)
      )
    );
  });

  // Handlers
  const handleStatusChange = (status) => {
    setStatusFilter(status);
    setPage(1);
  };

  const handleRefresh = () => {
    refetch();
    toast.success('Refreshed!');
  };

  // Handle status update - tracking is auto-generated by backend
  const handleStatusUpdate = (orderId, newStatus) => {
    statusMutation.mutate({ orderId, status: newStatus });
  };

  const handleRowClick = (order) => {
    setSelectedOrder(order);
  };

  const handleCloseModal = () => {
    setSelectedOrder(null);
  };

  return (
    <div className="space-y-6">
      {/* Order Details Modal */}
      {selectedOrder && (
        <OrderDetailsModal 
          order={selectedOrder} 
          onClose={handleCloseModal} 
        />
      )}
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold text-gray-900">Orders</h1>
          <p className="text-gray-500 mt-1">
            Manage and track customer orders
          </p>
        </div>
        
        <button
          onClick={handleRefresh}
          disabled={isFetching}
          className="inline-flex items-center gap-2 px-4 py-2 bg-white border border-gray-300 rounded-lg text-sm font-medium text-gray-700 hover:bg-gray-50 disabled:opacity-50 transition-colors"
        >
          <RefreshCw className={`w-4 h-4 ${isFetching ? 'animate-spin' : ''}`} />
          Refresh
        </button>
      </div>

      {/* Search */}
      <div className="relative">
        <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-5 h-5 text-gray-400" />
        <input
          type="text"
          placeholder="Search by order #, SKU, or product name..."
          value={searchQuery}
          onChange={(e) => setSearchQuery(e.target.value)}
          className="w-full pl-10 pr-4 py-2.5 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500 transition-colors"
        />
      </div>

      {/* Status Tabs */}
      <StatusTabs
        currentStatus={statusFilter}
        onStatusChange={handleStatusChange}
        counts={statusCounts}
      />

      {/* Content */}
      <div>
        {/* Loading */}
        {isLoading && (
          <div className="flex flex-col items-center justify-center py-12 bg-white rounded-xl border border-gray-200">
            <RefreshCw className="w-8 h-8 text-blue-500 animate-spin mb-4" />
            <p className="text-gray-500">Loading orders...</p>
          </div>
        )}

        {/* Error */}
        {isError && (
          <div className="flex flex-col items-center justify-center py-12 bg-red-50 rounded-xl border border-red-200">
            <AlertCircle className="w-8 h-8 text-red-500 mb-4" />
            <p className="text-red-700 font-medium">Failed to load orders</p>
            <p className="text-red-500 text-sm mt-1">{error?.message}</p>
            <button
              onClick={() => refetch()}
              className="mt-4 px-4 py-2 bg-red-100 text-red-700 rounded-lg hover:bg-red-200 transition-colors"
            >
              Try Again
            </button>
          </div>
        )}

        {/* Empty */}
        {!isLoading && !isError && filteredOrders.length === 0 && (
          <div className="flex flex-col items-center justify-center py-16 bg-white rounded-xl border border-gray-200">
            <div className="w-16 h-16 bg-gray-100 rounded-full flex items-center justify-center mb-4">
              <Inbox className="w-8 h-8 text-gray-400" />
            </div>
            <h3 className="text-lg font-medium text-gray-900 mb-1">
              {searchQuery ? 'No orders found' : 'No orders yet'}
            </h3>
            <p className="text-gray-500 text-center max-w-sm">
              {searchQuery 
                ? `No orders match "${searchQuery}".`
                : statusFilter !== 'all'
                  ? `No ${ORDER_STATUS[statusFilter]?.label.toLowerCase()} orders.`
                  : 'Orders will appear here when customers purchase.'
              }
            </p>
          </div>
        )}

        {/* Table */}
        {!isLoading && !isError && filteredOrders.length > 0 && (
          <OrdersTable
            orders={filteredOrders}
            onStatusUpdate={handleStatusUpdate}
            onRowClick={handleRowClick}
          />
        )}
      </div>

      {/* Pagination */}
      {!isLoading && pagination.totalPages > 1 && (
        <div className="flex items-center justify-between bg-white px-4 py-3 rounded-lg border border-gray-200">
          <p className="text-sm text-gray-600">
            {((page - 1) * limit) + 1}-{Math.min(page * limit, pagination.totalCount)} of {pagination.totalCount}
          </p>
          <div className="flex items-center gap-2">
            <button
              onClick={() => setPage(p => Math.max(1, p - 1))}
              disabled={page === 1 || isFetching}
              className="px-3 py-1.5 border border-gray-300 rounded-lg text-sm text-gray-700 hover:bg-gray-50 disabled:opacity-50 disabled:cursor-not-allowed"
            >
              Previous
            </button>
            <span className="px-3 py-1.5 text-sm text-gray-600">
              {page} / {pagination.totalPages}
            </span>
            <button
              onClick={() => setPage(p => Math.min(pagination.totalPages, p + 1))}
              disabled={page === pagination.totalPages || isFetching}
              className="px-3 py-1.5 border border-gray-300 rounded-lg text-sm text-gray-700 hover:bg-gray-50 disabled:opacity-50 disabled:cursor-not-allowed"
            >
              Next
            </button>
          </div>
        </div>
      )}
    </div>
  );
}